name: Polite Type
favicon: null
layout_spectrum: 0.23625
typography_spectrum: 0.463
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d6e2df'
    - '#ec4e40'
    - '#a7b1ea'
    - '#f6d20b'
    - '#245279'
  brandStrength: 1
  lightness: 0.6467920590657741
  saturation: 0.7445133649744093
  rhythmicContrast: 0.6361945474054664
purpose: []
